[build]
  command = "npm run build"
  publish = "dist"

# Define cabeçalhos para arquivos JavaScript
[[headers]]
  for = "/*.js"  # APLICA SOMENTE A ARQUIVOS .JS
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Se você tiver arquivos .css no assets e quiser garantir, pode adicionar outra regra
# [[headers]]
#   for = "/*.css"
#   [headers.values]
#     Content-Type = "text/css; charset=utf-8"
#     X-Content-Type-Options = "nosniff"